<?php

/**
 * @file
 * Provides a password field webform component
 */

/**
 * Implements hook_webform_component_info().
 */
function webform_password_component_webform_component_info() {
  $component = array(
    'password' => array(
      'label' => t('Password'),
      'description' => t('Password protects a webform'),
      'features' => array(
        'csv' => FALSE,
        'default_value' => FALSE,
        'description' => FALSE,
        'email' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'title_display' => FALSE,
        'private' => FALSE
      ),
      'file' => 'components/password.inc',
    ),
  );

  return $component;
}
